<form id="msb" action="https://loveangels.ie/catalogsearch/result/" method="get">
    <div class="field search">
        <div class="control">
            <input id="msbi" type="text" name="q" value="" placeholder="Search: vibrator, cock ring" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both"autocomplete="off" aria-expanded="false">
        </div>
    </div>
    <div class="actions">
        <button type="submit" title="Search" class="action search" aria-label="Search">
            <span>SEARCH</span>
        </button> 
        <a title="close" class="action close" onclick="toggleSearch()">
            <span class="icon"></span> 
            <span class="text">close</span>
        </a>
    </div>
</form>
<form id="dsb" action="https://loveangels.ie/catalogsearch/result/" method="get" class="hide-checkout">
    <div class="field search">
        <div class="control">
            <input id="dsbi" type="text" name="q" value="" placeholder="Search: vibrator, cock ring" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" aria-expanded="false">
        </div>
    </div>
    <div class="actions">
        <button type="submit" title="Search" class="action search" aria-label="Search">
            <span></span>
        </button>
    </div>
</form>
<div class="holder-start">
    <div id="menu-toggler" onclick="toggleMenu(this)">
        <div class="burger">
            <span aria-hidden="true"></span> 
            <span aria-hidden="true"></span> 
            <span aria-hidden="true"></span>
        </div>
        <span class="ilabelholder">
            <span class="ilabel" data-normal="menu" data-open="close"></span>
        </span>
    </div>
    <a class="m-logo" href="/">
        <span class="love">love</span>
        <span class="angels">angels</span>
    </a>
</div>